# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  steps:
    - run:
        command:
          - rm docs/eesrep-sphinx-sources/tutorials/*.ipynb
          - cp tutorials/*.ipynb docs/eesrep-sphinx-sources/tutorials/
          - cp README.md docs/eesrep-sphinx-sources/md_doc/
          - sed -i -e 's/docs\//..\/..\//g' docs/eesrep-sphinx-sources/md_doc/README.md
          
  tools:
    python: "3.8"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/eesrep-sphinx-sources/conf.py
   builder: "html"

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs_requirements.txt